<?php

return [
    'personal_and_company_info' => 'Personal and Company Information',
    'order_review' => 'Order Review',
    'domain_name' => 'Domain Name',
    'licence_uid' => 'Licence UID',
    'valid_until' => 'Valid Until',
    'payment_cost' => 'Payment Cost',
    'request_offer' => 'Request Offer',
    'email_title' => 'Offer request - ExpressLabelMaker.com',
    'offer_request' => 'Offer request',
    'licence_information' => 'Licence Information',
    'valid_from' => 'Valid From',
    'user_information' => 'User Information',
    'first_name' => 'First Name',
    'last_name' => 'Last Name',
    'email' => 'Email',
    'company_name' => 'Company Name',
    'company_address' => 'Company Address',
    'town' => 'Town',
    'country' => 'Country',
    'vat_number' => 'VAT Number',
    'email_footer' => 'This email was automatically generated by ExpressLabelMaker.com when payment data was submitted.',
];

